// Generated by CoffeeScript 1.3.3
(function() {

  (function($) {
    return $.fn.ajaxFrom = function(options) {
      if (options == null) {
        options = {};
      }
      ({
        settings: {}
      });
      return $.extend(settings, options);
    };
  })(jQuery);

}).call(this);
